// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaControleWebApi.Data;

#nullable disable

namespace SistemaControleWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("SistemaControleWebApi.Models.Request.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdFornecedor");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("SistemaControleWebApi.Models.Request.Pedido", b =>
                {
                    b.Property<int>("CodigoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DtPedido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fornecedor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Produto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtProduto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VlrTotalPedido")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoPedido");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("SistemaControleWebApi.Models.Request.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DtCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorProduto")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
